# Generated by Django 5.2.16 on 2026-07-21 01:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('core', '0001_initial'),
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('audiencia', 'Audiência'), ('reuniao', 'Reunião'), ('atendimento', 'Atendimento'), ('prazo', 'Prazo'), ('outro', 'Outro')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('local', models.CharField(blank=True, max_length=200)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado'), ('remarcado', 'Remarcado')], default='agendado', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='clientes.cliente')),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.escritorio')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='processos.processo')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_hora_inicio'],
            },
        ),
    ]
