# Generated by Django 5.2.16 on 2026-07-21 01:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_processo', models.CharField(blank=True, max_length=50)),
                ('area_juridica', models.CharField(choices=[('civel', 'Cível'), ('trabalhista', 'Trabalhista'), ('criminal', 'Criminal'), ('tributario', 'Tributário'), ('familia', 'Família'), ('previdenciario', 'Previdenciário'), ('empresarial', 'Empresarial'), ('outro', 'Outro')], max_length=20)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('aguardando', 'Aguardando'), ('suspenso', 'Suspenso'), ('arquivado', 'Arquivado'), ('encerrado', 'Encerrado')], default='ativo', max_length=20)),
                ('comarca_vara', models.CharField(blank=True, max_length=150)),
                ('valor_causa', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('data_distribuicao', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('advogado_responsavel', models.ForeignKey(blank=True, limit_choices_to={'role': 'advogado'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_responsavel', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='clientes.cliente')),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='core.escritorio')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
