# Generated by Django 5.2.16 on 2026-07-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='etapa_kanban',
            field=models.CharField(choices=[('novo_cliente', 'Novo Cliente'), ('atendimento', 'Atendimento'), ('documentacao', 'Documentação'), ('processo', 'Processo'), ('audiencia', 'Audiência'), ('finalizado', 'Finalizado')], default='novo_cliente', max_length=20),
        ),
    ]
