# Generated by Django 5.1.4 on 2026-07-15 02:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoAtendimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('area_juridica', models.CharField(max_length=100)),
                ('descricao_caso', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='pendente', max_length=20)),
                ('motivo_recusa', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('analisado_em', models.DateTimeField(blank=True, null=True)),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='core.escritorio')),
            ],
            options={
                'verbose_name': 'Solicitação de atendimento',
                'verbose_name_plural': 'Solicitações de atendimento',
                'ordering': ['-criado_em'],
            },
        ),
    ]
