# Generated by Django 5.1.4 on 2026-07-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoatendimento',
            name='urgente',
            field=models.BooleanField(default=False, help_text='Se marcado, a aprovação já cria o cliente automaticamente, sem etapa manual.'),
        ),
    ]
