# Generated by Django 5.1.4 on 2026-07-15 03:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendimento', '0002_solicitacaoatendimento_urgente'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_pessoa', models.CharField(choices=[('fisica', 'Pessoa física'), ('juridica', 'Pessoa jurídica')], default='fisica', max_length=10)),
                ('nome', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(blank=True, default='', max_length=18)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('endereco', models.CharField(blank=True, default='', max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='core.escritorio')),
                ('solicitacao_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_gerado', to='atendimento.solicitacaoatendimento')),
                ('usuario', models.OneToOneField(blank=True, help_text='Conta de login deste cliente. Pode ser nula até o acesso ser liberado.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
    ]
