# Generated by Django 5.2.16 on 2026-07-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escritorio',
            name='areas_atuacao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='escritorio',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='escritorio',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='escritorio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='escritorio',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='escritorio',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
