# Generated by Django 5.2.16 on 2026-07-21 02:27

import django.db.models.deletion
import documentos.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('core', '0001_initial'),
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('contrato', 'Contrato'), ('procuracao', 'Procuração'), ('peticao', 'Petição'), ('documento_pessoal', 'Documento Pessoal'), ('comprovante', 'Comprovante'), ('outro', 'Outro')], default='outro', max_length=30)),
                ('arquivo', models.FileField(upload_to=documentos.models.documento_upload_path)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='clientes.cliente')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_enviados', to=settings.AUTH_USER_MODEL)),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.escritorio')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='processos.processo')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
